### ISSUE TITLE
Button/Click-target to Focus Spotify app

### ISSUE THREAD

**Issue by syxanash** [will-stone/SpotSpot#13]
One feature that I find quite useful is the possibility to switch to Spotify app when clicking on the green label of the artist in the SS window as shown in the gif here:

![screen](https://i.imgur.com/CyfLFQE.gif)

I achieved this by doing something like this on the  `trackArtist` variable:

```js
trackArtist.addEventListener('click', () => {

    function execute(command, callback) {
        exec(command, (error, stdout, stderr) => { 
            callback(stdout); 
        });
    };

    const cmd = `osascript -e 'tell application "Spotify" to activate'`;

    // call the function
    execute(cmd, (output) => {
    });
});
```

**Comment by will-stone** [comment]
Nice! I’ll start adding new features like this once the React rewrite is complete. I think I’d probably prefer an open Spotify icon in the top right, as clicking the artist name may be confusing: I’d expect that to jump to the artist. But I’ll experiment as we still want SS to operate when in tiny mode without feeling cramped.

**Comment by will-stone** [comment]
The React rewrite is nearly done. I tried a little Spotify icon in the top-right but it did feel a bit cramped when SS is small. Also, the click target was a bit small. I've gone with double-click to open Spotify instead; stopping propagation on the controls so you can still quickly click-though tracks without accidentally opening Spotify on fast clicks.

**Comment by syxanash** [comment]
do you mean double click anywhere on the window? anyway it sounds like a better approach!
I initially decided to click the artist title because it has the green label hence Spotify main color, but yours sounds better.

**Comment by will-stone** [comment]
Thanks. Yeah, the whole of the widget is double-clickable now (except the buttons). I've got the latest version on my work machine today to give me an idea of if I like the changes I've made. Feel free to download the source and compile the `react-rewrite` branch, just bear in mind it's subject to change.

**Comment by will-stone** [comment]
In v3, please try it out and let me know your thoughts: https://github.com/will-stone/SpotSpot/releases/tag/v3.0.0

**Comment by syxanash** [comment]
Nice one, `open -a spotify` is way better than what I initially went for 😂
Love the new version, good work man!
