### ISSUE TITLE
Add Homebrew installation

### ISSUE THREAD

**Issue by will-stone** [will-stone/SpotSpot#21]
Brew could be an easier way for users to upgrade. Need to research it; have never made a brew package before, so if someone stumbles upon this and would like to help, that'd be great! 😄

**Comment by briantully** [comment]
Hey there Will - 

I've added a PR for a spotspot homebrew cask at https://github.com/Homebrew/homebrew-cask/pull/53982

**Comment by will-stone** [comment]
Thanks! That's awesome! So how does it work? If I make an update to SpotSpot, do we also have to put in a PR on the homebrew-cask repo?

**Comment by briantully** [comment]
Yes, I believe that’s the process. All we’d need to do to update the cask is update the spotspot.rb file with updated values for the following fields:

```
version
sha256
url
```
I followed the instructions on https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

Hope that helps!

**Comment by briantully** [comment]
Yes, I believe that’s the process. All we’d need to do to update the cask
is update the spotspot.rb file with updated values for the following fields:

version
sha256
url

I followed the instructions on
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

Hope that helps!

Regards,
Brian


2018-10-22 16:50:49 +0000 Will Stone <notifications@github.com> :

**Comment by briantully** [comment]
This has been merged to homebrew-cask master :)

https://github.com/Homebrew/homebrew-cask/pull/53982

**Comment by will-stone** [comment]
Thanks Brian! Cheers.
