### ISSUE TITLE
Very slow to respond to events/interactions on Mojave

### ISSUE THREAD

**Issue by will-stone** [will-stone/SpotSpot#24]
Clicking pause/next-song and responding to state changes are very slow on macOS Mojave 😭

**Comment by syxanash** [comment]
had the same problem today :( any idea what it might be related to?

**Comment by will-stone** [comment]
I logged the issue here: https://github.com/electron/electron/issues/16166 Please +1 it for visibility.

**Comment by will-stone** [comment]
I decided to bite the bullet and get an Apple Developer account. This means the release is now signed and this bug is officially fixed. However, this now means I incur a yearly cost of £79. Therefore, please consider a donation if you use the app. Thanks.

[![ko-fi](https://www.ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/Z8Z7V0KF)
