### ISSUE TITLE
Any way keep controls and song info visible permanently?

### ISSUE THREAD

**Issue by briantully** [will-stone/SpotSpot#25]
I noticed that the controls and song title only stay visible for a few seconds and SpotSpot reverts back to the album art.

I'd like to be able to mouseover SpotSpot display to show the song/artist info and controls, but also to click something in order to keep the display at this view (i.e., always show song/artist info and controls) rather than switching back to the album art. I thought at one point SpotSpot allowed this, but now it doesn't.

Perhaps when switching to the song/artist info and controls view you can have the album art showing in the background using tranparency? I don't know why it needs to be an either/or choice. It would be awesome of all items (song/artist info + controls + album art) could be displayed in the same view/window.

Thanks!

**Comment by will-stone** [comment]
I use SpotSpot in a very small window and find the current behaviour works really well for me. At the end of the day, this is just an Electron app and making a fork, and tweaking some CSS values wouldn't be too much effort. If you do decide to do this, please link back here as I'd love to see what your take on it is. Also, all releases are left on GitHub so if a newer version isn't to your tastes, there is no pressure to upgrade.

**Comment by briantully** [comment]
I just put up a PR at https://github.com/will-stone/SpotSpot/pull/29 which is my simple take to illustrate my preferred use case :)
