### ISSUE TITLE
What was missing all along! ✨

### ISSUE THREAD

**Issue by mysticaltech** [will-stone/SpotSpot#32]
Oh man, you don't know how many times I went to Spotify's preferences looking for that feature and never found it, but here it is, thank you...

**Comment by will-stone** [comment]
Glad you like it 😄

**Comment by mysticaltech** [comment]
If I could add a little feature request to consider, find a way to fit the "heart" button in there, to be able to train the recommendation engine lol. It would be added sugar!

**Comment by will-stone** [comment]
I'm not sure that API is exposed. My flow when I like a song is to double click SpotSpot to open Spotify and heart it from there.

**Comment by mysticaltech** [comment]
Ah cool, didn't know it was double-clickable, will do that too! 🙏🏻
