### ISSUE TITLE
Move electron window across desktops when switching

### ISSUE THREAD

**Issue by paragbhtngr** [will-stone/SpotSpot#7]
As of now, the window stays on the same desktop it was created on. It would be good if it moved to the active desktop on swiping left or right to a new desktop

**Comment by will-stone** [comment]
The answer may lie here: https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetalwaysontopflag-level-relativelevel

Feel free to have a play and offer a pull request.

**Comment by syxanash** [comment]
may I take this? I think I found a way to solve this problem 😄

**Comment by will-stone** [comment]
@syxanash go for it. I'll take a look at your PR later. I'm actively working on SS again (I'm moving the view code over to React which will mean I'll be able to add some nice animations and transitions).

**Comment by will-stone** [comment]
Fixed in v2.2.0 https://github.com/will-stone/SpotSpot/releases/tag/v2.2.0
