### ISSUE TITLE
Allow setting a default window size or remember window size

### ISSUE THREAD

**Issue by briantully** [will-stone/SpotSpot#8]
Thanks for developing this great utility!

One thing I've noticed is that when I open SpotSpot, the window size is tiny -- where the text is not really legible. I was wondering if there was a way to allow setting a default window size and/or remembering the window size if it gets resized the next time SpotSpot is opened.

**Comment by will-stone** [comment]
Thanks for suggestion, Brian. I'm thinking about adding some upgrades to SpotSpot and this seems like a sensible addition to incorporate into that. I can't give any estimates as I'm rather busy at the moment; you are welcome to take a look at the code (it's very simple) and send a pull-request if you'd like it sooner.

**Comment by will-stone** [comment]
This is in v3.1.x and above. You can download the latest version from the homepage: https://will-stone.github.io/SpotSpot/
